# Generated by Django 4.0.6 on 2022-08-03 21:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_user', models.CharField(max_length=30)),
                ('a_user', models.CharField(max_length=30)),
                ('mensaje', ckeditor.fields.RichTextField()),
                ('fecha_mensaje', models.DateTimeField(null=True)),
            ],
        ),
    ]
