# Generated by Django 4.0.6 on 2022-08-29 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_descripcion_user_masdatosusuario_descripcion'),
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='a_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.masdatosusuario'),
        ),
    ]
