# Generated by Django 4.0.6 on 2022-08-29 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensajeria', '0002_alter_mensajeria_a_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='a_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
