# Generated by Django 4.0.5 on 2022-07-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=30)),
                ('tara', models.IntegerField(null=0)),
                ('ejes', models.IntegerField(null=0)),
                ('fecha_creacion', models.DateTimeField(null=True)),
            ],
        ),
    ]
