# Generated by Django 4.0.5 on 2022-07-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='fecha_creacion',
        ),
    ]
