# Generated by Django 4.0.6 on 2022-08-01 23:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosteosUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=15)),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('titulo', models.CharField(max_length=15)),
                ('sub_titulo', models.CharField(max_length=30)),
                ('posteo', ckeditor.fields.RichTextField()),
                ('fecha_posteo', models.DateTimeField(null=True)),
            ],
        ),
    ]
