# Generated by Django 4.0.6 on 2022-07-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteosusuarios',
            name='autor',
            field=models.CharField(max_length=15),
        ),
    ]
