# Generated by Django 4.0.6 on 2022-08-02 01:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0002_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
