# Generated by Django 4.0.6 on 2022-08-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0005_posteosusuarios_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteosusuarios',
            name='usuario',
        ),
    ]
