# Generated by Django 4.0.6 on 2022-07-31 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_masdatosusuario_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masdatosusuario',
            name='descripcion',
        ),
    ]
