# Generated by Django 4.0.6 on 2022-07-31 20:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_masdatosusuario_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='masdatosusuario',
            name='descripcion_user',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
