# Generated by Django 4.0.6 on 2022-07-31 20:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_masdatosusuario_descripcion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masdatosusuario',
            name='descripcion_user',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
