# Generated by Django 4.0.6 on 2022-07-31 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_masdatosusuario_descripcion_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masdatosusuario',
            old_name='descripcion_user',
            new_name='descripcion',
        ),
    ]
